name: Tests

on: [ push, pull_request ]

env:
  # The hostname used to communicate with the Redis service container
  REDIS_HOST: redis
  # The default Redis port
  REDIS_PORT: 6379
  # Composer cache directory
  COMPOSER_CACHE_DIR: ~/.composer/cache
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        php: [ 7.2, 7.3, 7.4 ]
        redis-version: [ 6 ]

    name: P${{ matrix.php }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: redis, apc, apcu
          coverage: none

      - name: Install dependencies
        run: make install

      - name: Start Redis
        uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - name: Run Codestyle checker
        run: make codestyle

      - name: Execute tests
        run: make test
